hyperlane-xyz/hyperlane-warp-ui-template

- CUSTOMIZE.md
- package.json
- src/components/nav/Footer.tsx
- src/components/tip/TipCard.tsx
- src/consts/config.ts
- src/features/tokens/routes.ts
- src/features/transfer/TransferTokenForm.tsx
- src/features/transfer/TransferTransactionsModal.tsx
- src/pages/index.tsx
- yarn.lock
- Fix balance fetching and add recipient balance fetching
- Update SDK to 1.0.0
- Add details to Customize instructions
- Make tip card easy to hide
- Fix summary text in spinner modal
> Usability improvements and balance fixes

- src/components/icons/TokenIcon.tsx
- src/consts/chains.json
- src/features/chains/metadata.ts
- src/features/tokens/TokenSelectField.tsx
- src/features/tokens/metadata.ts
- src/features/tokens/routes.ts
- src/utils/url.ts
- Make token logoURI optional
- Rename logoImgSrc to logoURI and make optional for chain config
- Use collateral chain as default from chain in form
- Reorganize routes.ts code
> Address some feedback from warp deployment

- src/components/toast/TxSuccessToast.tsx
- src/consts/tokens.ts
- src/features/chains/ChainSelectField.tsx
- src/features/chains/ChainSelectModal.tsx
- src/features/chains/utils.ts
- src/features/contracts/hypErc20.ts
- src/features/multiProvider.ts
- src/features/tokens/TokenListModal.tsx
- src/features/tokens/TokenSelectField.tsx
- src/features/tokens/metadata.ts
- src/features/tokens/routes.ts
- src/features/tokens/types.ts
- src/features/tokens/useTokenBalance.tsx
- src/features/tokens/utils.ts
- src/features/transfer/TransferTokenForm.tsx
- src/features/transfer/TransfersStatusModal.tsx
- src/features/transfer/types.ts
- src/features/transfer/useTokenTransfer.ts
- src/global.d.ts
- Add support for HypNative tokens
- Modify token list schema to reduce ambiguity
- Create global ChainId and DomainId type aliases for clarity 
Corresponds with https://github.com/hyperlane-xyz/hyperlane-deploy/pull/49
> HypNative support

- src/features/tokens/TokenListModal.tsx
This PR tries to fix the https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2514
Features of the PR
- Grays out not selectable
- Adds a tooltip mentioning the reason (Not suitable for source chain to destination chain) (Need to hover on `i`)
- Search bar works as it is
Video, demonstrating the changes is attested below, have a look
https://github.com/hyperlane-xyz/hyperlane-warp-ui-template/assets/66910385/08f03af4-861e-40ca-b78a-45c796a2e757
> Token select fix for issue: 2514

- src/features/transfer/useTokenTransfer.ts
Was not working, so catching this here for now
> Catch destination balance checking

- src/consts/chains.ts
- src/consts/config.ts
- src/consts/tokens.ts
- src/features/multiProvider.ts
- src/features/tokens/TokenListModal.tsx
- src/features/tokens/adapters/AdapterFactory.ts
- src/features/tokens/adapters/EvmTokenAdapter.ts
- src/features/tokens/adapters/ITokenAdapter.ts
- src/features/tokens/adapters/SealevelTokenAdapter.ts
- src/features/tokens/balances.tsx
- src/features/tokens/contracts/sealevelSerialization.ts
- src/features/tokens/metadata.ts
- src/features/tokens/routes/hooks.ts
- src/features/tokens/routes/types.ts
- src/features/tokens/types.ts
- src/features/transfer/TransferTokenForm.tsx
- src/features/transfer/TransfersDetailsModal.tsx
- src/features/transfer/useTokenTransfer.ts
- src/features/wallet/EvmWalletContext.tsx
- src/features/wallet/SideBarMenu.tsx
- src/features/wallet/hooks.tsx
- src/utils/addresses.ts
- src/utils/amount.ts
https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2548
- Make name, symbol, decimals optional in config
- Check collateral contract balance before transfer
- Add option to hide disabled tokens in modal
- Tweak sidebar styles
- Add fixes from Nautilus preparations
> Add partial support for multiple collateral / native chains for a token

- .github/workflows/ci.yml
- src/features/transfer/TransferTokenForm.tsx
- src/features/wallet/hooks.tsx
- src/utils/amount.ts
Hoisted up from @tkporter PR #54 
- Improve formatting of small amounts
- Fix typo in wallet hooks
> Improve formatting of small amounts

- src/consts/config.ts
- src/features/transfer/TransferTokenForm.tsx
- src/global.d.ts
- Add support for route blacklist via NEXT_PUBLIC_TRANSFER_BLACKLIST env var
- Fix outdated CAIP2 example comment
> Add support for a transfer route blacklist

- src/consts/config.ts
- src/features/transfer/TransferTokenForm.tsx
- src/features/transfer/useTokenTransfer.ts
- src/global.d.ts
- Includes #59 
- Adds a warning if there aren't enough funds to cover interchain gas payments. Atm this is pretty late in the tx flow and quite ugly. We should probably consider adding a "fees" section to the main tx builder UI bit so this is extra clear -- I anticipate this being a point of confusion. Fees to go to BSC are about 15 ZBC and to Solana about 10 ZBC (ZBC is about 1 cent in value)
> Prepping for removal of deposit only

- src/components/toast/IgpDetailsToast.tsx
- src/consts/links.ts
- src/features/multiProvider.ts
- src/features/store.ts
- src/features/tokens/AdapterFactory.ts
- src/features/tokens/approval.ts
- src/features/tokens/balances.ts
- src/features/tokens/routes/utils.ts
- src/features/transfer/TransferTokenForm.tsx
- src/features/transfer/useIgpQuote.ts
- src/features/transfer/useTokenTransfer.ts
Fixes https://github.com/hyperlane-xyz/hyperlane-warp-ui-template/issues/61
Supersedes https://github.com/hyperlane-xyz/hyperlane-warp-ui-template/pull/60 which should be removed from eclipse-mainnet
> Implement IGP fee details and validation

- next.config.js
- src/features/wallet/hooks.tsx
- Fix WalletConnect connections for cosmos by using undocumented `useChains` hook
- Fix image load errors in WalletConnect modal by adjusting CSP header
> WalletConnect fixes

- src/features/transfer/TransferTokenForm.tsx
- Use gas token symbol in toast
- Migrate igp payment checking improvement to main
> IGP payment validation clarification

- src/features/transfer/TransferTokenForm.tsx
- src/features/wallet/hooks.tsx
Fixes https://github.com/hyperlane-xyz/hyperlane-warp-ui-template/issues/84#event-11024996890
> Ensure self button uses correct cosmos chain

- src/features/transfer/TransferTokenForm.tsx
Fixes https://github.com/hyperlane-xyz/hyperlane-warp-ui-template/issues/92
> Validate cosmos recipient address bech32 prefix

- src/features/transfer/useIgpQuote.ts
- src/features/transfer/validateForm.ts
Approved via https://github.com/hyperlane-xyz/hyperlane-warp-ui-template/pull/105
> Fix igp quotes for ibc-based routes

- sentry.default.config.js
Fixes https://github.com/hyperlane-xyz/issues/issues/1043
> Define sentry error filter list

- src/components/icons/WalletLogo.tsx
- src/features/transfer/TransfersDetailsModal.tsx
- src/features/wallet/SideBarMenu.tsx
- src/features/wallet/WalletControlBar.tsx
- src/features/wallet/hooks/cosmos.ts
- src/features/wallet/hooks/evm.ts
- src/features/wallet/hooks/multiProtocol.tsx
- src/features/wallet/hooks/solana.ts
- src/features/wallet/hooks/types.ts
Fixes #180 
Group addresses by protocol and show wallet logos
> feat: New sidebar wallet button design

- src/middleware.ts
- src/pages/blocked.tsx
https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/1868
> Geoblocking

- src/components/nav/Footer.tsx
> black footer logos

- src/consts/warpRoutes.yaml
Updates the config to the warp route that includes fraxtal
> Add new warp route with Fraxtal

- next.config.js
- package.json
- yarn.lock
- Lockdown next images and CSP style sources
- Upgrade Next related libs
Fixes https://github.com/hyperlane-xyz/issues/issues/1321
> Lockdown image and style sources

- next.config.js
- package.json
- src/pages/_app.tsx
- src/vendor/inpage-metamask.js
- yarn.lock
> Injective image patch

- src/features/tokens/balances.ts
Proxy for #204 to fix the lint and formatting issues
> fix: Balance checking stale values

- .github/workflows/create-merge-prs.yaml
feat: workflow to auto create PRs to merge main
> feat: workflow to auto create PRs to merge main

- src/components/tip/TipCard.tsx
- src/consts/config.ts
- src/features/transfer/TransferTokenForm.tsx
> Add destination blacklist and update tip card text

- src/components/nav/Header.tsx
- src/pages/index.tsx
- landing page for nautilus shutdown message
> feat(warpui): Nautilus shutdown

- package.json
- src/consts/warpRouteWhitelist.ts
- yarn.lock
feat: update to registry v4.3.5
> feat: update to registry v4.3.5

- src/components/nav/Footer.tsx
- src/consts/links.ts
- Added links to `terms`, `privacy` and `bounty` in `Footer`
- Refactored the two arrays of `footerLinks` into just one
> feat: add terms, privacy and bounty links

- src/components/nav/Header.tsx
- src/pages/index.tsx
Reverts hyperlane-xyz/hyperlane-warp-ui-template#239
> Revert "feat(warpui): Nautilus shutdown"

- next.config.js
- sentry.client.config.js
- sentry.default.config.js
- sentry.edge.config.js
- sentry.server.config.js
- src/instrumentation.ts
- src/pages/_document.tsx
https://docs.sentry.io/platforms/javascript/guides/nextjs/migration/v7-to-v8/
Tested locally with a personal Sentry project
> fix: Sentry v7 to v8 migration issues

- src/features/chains/ChainSelectField.tsx
- src/features/chains/ChainSelectModal.tsx
- src/features/chains/hooks.ts
- src/features/chains/utils.ts
- src/features/transfer/TransferTokenForm.tsx
Builds on https://github.com/hyperlane-xyz/hyperlane-warp-ui-template/pull/323 but resolves conflicts and improves the picker custom field data
> feat: Replace chain picker with new ChainSearchMenu from Widgets lib

- src/components/input/TextField.tsx
- src/consts/config.ts
- src/features/tokens/SelectOrInputTokenIds.tsx
- src/features/tokens/TokenListModal.tsx
- src/features/transfer/TransferTokenForm.tsx
- Autofocus text input field
- Make appearance more consistent with chain picker
- Hide disabled tokens by default
> feat: Improve UX of token list modal

- src/components/nav/Footer.tsx
- src/consts/values.ts
- src/features/chains/metadata.ts
- src/features/store.ts
- src/features/transfer/TransfersDetailsModal.tsx
- src/features/wallet/context/CosmosWalletContext.tsx
- Fix errors in TransfersDetailsModal when metadata is missing
- Remove dead code in consts/values
- Avoid cosmoshub inclusion in chain picker
- Simplify footer links markup
> fix: Various leftover fixes from migration 

- src/features/chains/utils.ts
- src/utils/links.ts
Fix transfer details modal error for successful transfer when metadata is missing
> fix: transfer details modal error

- package.json
- src/consts/warpRouteWhitelist.ts
- src/features/tokens/warpCoreConfig.ts
- yarn.lock
Adds uBTC warp route to nexus whitelist and bumps registry version
> feat: add uBTC route to nexus

- package.json
- src/consts/warpRouteWhitelist.ts
- yarn.lock
Enables the kySOL warp route on the nexus ui
> feat: added kySOL warp route to whitelist

- package.json
- src/consts/warpRouteWhitelist.ts
- yarn.lock
feat: enable INTERN route on inevm ui
registry PR https://github.com/hyperlane-xyz/hyperlane-registry/pull/432
> feat: enable INTERN route on inevm ui

- src/consts/chains.ts
- intended to be a quick fix for some injective RPC 502s being seen
- partner to https://github.com/hyperlane-xyz/hyperlane-warp-ui-template/pull/369
> feat: allow Injective RPC to be overridden

- src/consts/chains.ts
- intended to be a quick fix for some injective RPC 502s being seen
> fix: allow Injective RPC to be overridden

- CUSTOMIZE.md
- src/consts/links.ts
Fix typo: "These are images" -> "These images"
fix: update Twitter URL to x.com format
> Fix typo: "These are images" -> "These images"fix: update Twitter URL to x.com format 

- package.json
- yarn.lock
> feat: Up registry to 6.12

- src/consts/warpRoutes.ts
Context: https://discord.com/channels/935678348330434570/935679524534911007/1327223536561164390
In response to a Stride protocol fee increase they had, fees are now 0.5 TIA
Tested it worked!
> fix: increase Celestia -> Stride fees

- package.json
- src/consts/chains.ts
- src/consts/warpRouteWhitelist.ts
- yarn.lock
- Adds `SOL/solanamainnet-soon` and `Bonk/solanamainnet-soon`
> feat: Add SOL and Bonk between Solana and SOON

- package.json
- src/consts/warpRouteWhitelist.ts
- yarn.lock
- Adds `TONY/base-solanamainnet`
> feat: add TONY to Nexus

- package.json
- src/consts/warpRouteWhitelist.ts
- src/consts/warpRoutes.yaml
- yarn.lock
> Reference registry version of TRUMP

- src/consts/chains.ts
- src/consts/config.ts
- Turn TipCard off
- Remove eclipse from chains
> fix: remove eclipse chain and tip card

- package.json
- yarn.lock
Update registry for stride fee in nexus branch
please see https://github.com/hyperlane-xyz/hyperlane-registry/pull/505
> chore: update registry

- src/components/buttons/ConnectAwareSubmitButton.tsx
- src/components/buttons/SolidButton.tsx
- src/features/tokens/balances.ts
- src/features/transfer/RecipientConfirmationModal.tsx
- src/features/transfer/TransferTokenForm.tsx
- Create recipient confirmation modal
- Check recipient balance before transition to Review step
- Rename SolidButton classes prop
> feat: Add recipient confirmation modal

- src/consts/app.ts
Updated trump app `name`, `description` and `url`
Tested routes from SOL <> ARB and SOL <> OP
> chore(trump): update app settings

- src/consts/warpRouteWhitelist.ts
Adds the `JitoSOL` route to the whitelist
> feat: add jito sol route

- package.json
- src/consts/warpRouteWhitelist.ts
- yarn.lock
Adds `SMOL/arbitrum-ethereum-solanamainnet-treasure` to Nexus
> feat: add SMOL to Nexus

- package.json
- src/consts/warpRouteWhitelist.ts
- yarn.lock
add Unichain and berachain to EZETH whitelist
> feat: add Unichain and berachain to EZETH

- src/consts/warpRouteWhitelist.ts
- Adds LOGX/arbitrum-solanamainnet
> feat: add LOGX/arbitrum-solanamainnet

- package.json
- src/consts/warpRouteWhitelist.ts
- src/consts/warpRoutes.yaml
- yarn.lock
- Adds CDX/base-solanamainnet to Nexus
> feat: add CDX/base-solanamainnet to nexus

- package.json
- src/consts/warpRouteWhitelist.ts
- yarn.lock
feat: add hyperevm routes
- ETH
- WBTC
- USDT
> feat: add hyperevm routes

- package.json
- src/consts/warpRouteWhitelist.ts
- yarn.lock
- Add SOL/hyperevm-solanamainnet
> feat: add SOL/hyperevm-solanamainnet

- package.json
- src/consts/warpRouteWhitelist.ts
- yarn.lock
> feat: Add REZ warp route

- package.json
- yarn.lock
Update registry to version 10.11.1
> chore: update registry version

- package.json
- yarn.lock
This PR Updates Registry to 10.13.0
> chore: Update Registry to 10.13.0

- package.json
- yarn.lock
Upgrades registry version to 10.14.0
> chore: upgrade registry to 10.14.0

- package.json
- yarn.lock
This PR ups the registry version to 10.15.0
> chore: Up Registry to 10.15.0

- src/consts/warpRouteWhitelist.ts
> feat: add GPS warpId

- package.json
- src/consts/warpRouteWhitelist.ts
- yarn.lock
Adds:
- cdx/base solanamainnet sophon
- uBTC/boba-bsquared-soneium-swell
> feat: updated registry versio nand added updated routes ids

- package.json
- yarn.lock
> chore: upgrade registry version

- package.json
- src/consts/warpRouteWhitelist.ts
- yarn.lock
- Add oUSDT warp route
- Upgrade registry to patch version
> chore: add oUSDT warp route to nexus

- src/consts/warpRouteWhitelist.ts
This PR adds Superseed USDC extension
> feat: Add superseed usdc

- .github/workflows/ci.yml
- .github/workflows/create-merge-prs.yaml
Include oUSDT branch in workflows
> ci: add oUSDT to CI branch configs

- package.json
- yarn.lock
> chore: upgrade registry

- src/consts/warpRouteWhitelist.ts
- At the request of the Treasure team
> chore: remove MAGIC from Nexus

- src/components/tip/TipCard.tsx
- src/consts/config.ts
Add tip card to link to treasure UI for MAGIC transfers
> chore: add tip card for magic transfers

- package.json
- src/consts/warpRouteWhitelist.ts
- yarn.lock
Adds the remaining 4 warp routes from the soon wr deployment batch
> feat: soon second wr batch

- package.json
- yarn.lock
Upgrade all hyperlane packages and version
> chore: upgrade hyperlane packages

- package.json
- src/components/icons/TokenIcon.tsx
- src/consts/chains.ts
- src/consts/links.ts
- src/features/chains/metadata.ts
- src/features/store.ts
- yarn.lock
- Change `GithubRegistry` to use `PartialRegistry`
- Change `Token` and `Chain` logo link to hard-coded link path
- Modify RPC URL overrides logic to: if `EVM` chain, add override at the end, otherwise in the front
- Upgrade registry
> chore: partial registry and change image and RPC url logic

- package.json
- yarn.lock
Bumps regestry dep to the latest version
> chore: bump registry to latest version

- src/consts/warpRouteWhitelist.ts
> feat: hyper routes

- src/features/chains/ChainConnectionWarning.tsx
Increase refetch interval of the RPC health check
> chore: increase rpc health check timeout

- package.json
- yarn.lock
This PR bumps registry to 13.7.1
> chore: Bump registry to 13.7.1

- src/components/tip/TipCard.tsx
Updated style and text for tip card
> chore: update tip card

- package.json
- yarn.lock
> chore: Up Registry to 13.9.0

- .github/workflows/ci.yml
- src/features/tokens/balances.ts
- Increase refetch interval for fetching balances to 30 seconds
- Updated workflow to be run in merge queue
> chore: increase refetch interval for useBalance

- src/consts/warpRouteWhitelist.ts
Add Apechain EVM warp routes to warp route white list
Tested in UI:
> feat: apechain EVM routes

- package.json
- yarn.lock
This PR bumps up registry to 15.4.0
> chore: Bump up registry to 15.4.0

- package.json
- src/consts/warpRouteWhitelist.ts
- yarn.lock
This PR merge main to nexus and add TGT route
> chore: Merge main to nexus and add TGT route

- package.json
- yarn.lock
> chore: Bump up registry to 15.5.0

- package.json
- src/consts/warpRouteWhitelist.ts
- yarn.lock
This PR merges main to nexus with Registry@15.5.0 and subtensor USDC
> chore: main to nexus with Registry@15.5.0 and subtensor USDC

- package.json
- yarn.lock
This pr bumps registry to 15.7.1
> chore: bump registry to 15.7.1

- package.json
- src/consts/warpRouteWhitelist.ts
- yarn.lock
This PR Bumps registry to 17.6.0 and add Matchain
> chore: Bump registry to 17.6.0 and add Matchain

- package.json
- yarn.lock
> chore: Bump registry to 17.7.0

- src/consts/warpRouteWhitelist.ts
Add fluence routes to nexus
FLT/fluence transactions:
[ethereum -> arbitrum](https://explorer.hyperlane.xyz/message/0xfb11a97a5e2f279fcc127a107090ba6a84d7f3ea9c235bdbfc01015c125ee86f)
[arbitrum -> ethereum](https://explorer.hyperlane.xyz/message/0xdd0e8875ba90943e85d5f9d6092a3d5f2c679a03ff46b2852ca53b109d51aa3d)
wpFLT/fluence transactions:
[fluence -> polygon](https://explorer.hyperlane.xyz/message/0xd7fff861504e5f64c5042d17363e45ad1d1365e6675d5ea48b30786f494aecd3)
[polygon -> fluence](https://explorer.hyperlane.xyz/message/0x1a158c25ca6dc25f97811401022ae9d89587906246821b93a7e8403d396acbd5)
> feat: fluence routes

- src/features/transfer/useTokenTransfer.ts
This PR adds multi tx signing support for the nexus UI. Note that this PR requires the monorepo PR to be merged and released first: https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/6607
> feat: add multi tx signing to ui

- src/consts/warpRouteWhitelist.ts
Updates the ES token warp route id
> chore: add es route extension to nexus

- src/consts/chains.ts
- src/consts/config.ts
- Active `shoulDisableChain` flag
- Disable `botanix`
- Enable `treasure`
> chore: active shouldDisableChain flag, update chains

- src/features/limits/const.ts
Update USDC multi-collateral route limits
- Add solanamainnet
- Bump to 10k USDC
> chore: update USDC limits on nexus

- package.json
- yarn.lock
> chore: bump registry

- src/consts/warpRouteWhitelist.ts
Add the PUMP/eclipsemainnet route to Nexus
> feat: add PUMP/eclipsemainnet route to whitelist

- src/components/tip/TipCard.tsx
- src/consts/warpRouteWhitelist.ts
> chore: Reenable Injective

- package.json
- yarn.lock
> chore: bump registry to 22.0.0

- src/consts/warpRouteWhitelist.ts
Include `INVT/solanamainnet-eclipsemainnet` route to nexus
Tested transactions
[solana -> eclipse](https://explorer.hyperlane.xyz/message/0xb3e5957e8881e9c227684352f3c7dbaf268f1a11a7a0658740cabb46bcb2660e)
[eclipse->solana](https://explorer.hyperlane.xyz/message/0xb540510647ca9672d7c041557acc593fc6a9291d02bd476aa8393641dc3e8c6c)
> feat: add INVT/solanamainnet-eclipsemainnet route

- src/components/tip/TipCard.tsx
Update TipCard with information about the upcoming domain change
> chore: update tip card for new domain

- src/consts/warpRouteWhitelist.ts
> feat: Add electroneum usdc

- src/pages/_document.tsx
Update plausible script with new domain and src
> chore: update plausible events script

- src/consts/warpRouteWhitelist.ts
> feat: Add electroneum usdt
