src/consts/tokens.ts
src/features/contracts/hypToken.ts
src/features/contracts/token.ts
src/features/tokens/SelectOrInputTokenIds.tsx
src/features/tokens/SelectTokenIdField.tsx
src/features/tokens/TokenListModal.tsx
src/features/tokens/TokenSelectField.tsx
src/features/tokens/metadata.ts
src/features/tokens/routes.ts
src/features/tokens/types.ts
src/features/tokens/useTokenBalance.tsx
src/features/transfer/TransferTokenForm.tsx
src/features/transfer/types.ts
src/features/transfer/useTokenTransfer.ts

- I added a config to. distinguish between ERC20 and ERC721
- if ERC721 decimals should be 0 to reuse balanceOf function from code
```
export const tokenList: WarpTokenConfig = [
// Example collateral token
{
type: 'collateral',
chainId: 5,
address: '0xb4fbf271143f4fbf7b91a5ded31805e42b2208d6',
hypCollateralAddress: '0x145de8760021c4ac6676376691b78038d3DE9097',
name: 'Weth',
symbol: 'WETH',
decimals: 18,
logoURI: '/logos/weth.png', // See public/logos/
isERC721: false,
},
{
type: "collateral",
chainId: 5,
address: "0xd03483b978461b3162CE9e4c80835b9E81E07018",
hypCollateralAddress: "0x1d30DD33886dE2914D610aDE55C55f5d145743AC",
name: "MyToken",
symbol: "MTK",
decimals: 0,       // 0 for ERC721
isERC721: true,  // distinguish between ERC20 and ERC721
},
....
```
Deploy warpRoute for ERC721 …

feat: implement warpRoute for ERC721

---

package.json
src/features/store.ts
src/features/transfer/types.ts
yarn.lock

Persist transfer history to local storage

---

src/consts/chains.ts
src/features/multiProvider.ts
src/features/transfer/TransferTokenForm.tsx
src/features/transfer/TransfersDetailsModal.tsx
src/features/wallet/SideBarMenu.tsx
src/utils/links.ts

Remove Hyperlane explorer link
Fix block explorer links
Show toast on recipient balance increase
Show toast from self button if wallet not connected Improve sidebar menu scrolling
Improve sidebar menu scrolling

Fixes and improvements for Eclipse branch

---

src/components/tip/TipCard.tsx
src/consts/config.ts
src/features/transfer/TransferTokenForm.tsx

This PR allows ENV var configuration of a whitelist of destination chains, to support a deposit-only mode for the UI

Support deposit-only mode

---

src/components/buttons/ConnectAwareSubmitButton.tsx
src/components/icons/ChainLogo.tsx
src/components/icons/TokenIcon.tsx
src/components/toast/TxSuccessToast.tsx
src/features/caip/chains.ts
src/features/caip/tokens.ts
src/features/chains/ChainSelectField.tsx
src/features/chains/ChainSelectModal.tsx
src/features/chains/utils.ts
src/features/multiProvider.ts
src/features/tokens/SelectOrInputTokenIds.tsx
src/features/tokens/SelectTokenIdField.tsx
src/features/tokens/TokenListModal.tsx
src/features/tokens/TokenSelectField.tsx
src/features/tokens/adapters/AdapterFactory.ts
src/features/tokens/balances.tsx
src/features/tokens/metadata.ts
src/features/tokens/routes/hooks.ts
src/features/tokens/routes/types.ts
src/features/tokens/routes/utils.ts
src/features/tokens/types.ts
src/features/transfer/TransferTokenForm.tsx
src/features/transfer/TransfersDetailsModal.tsx
src/features/transfer/types.ts
src/features/transfer/useTokenTransfer.ts
src/features/wallet/SideBarMenu.tsx
src/features/wallet/hooks.tsx
src/global.d.ts
src/utils/links.ts

The Caip2 and Caip19 types were confusing for newcomers to the codebase.
This should clarify that caip2 IDs are for chains and Caip19 ids are for tokens

Rename CAIP var names for clarity

---

src/components/toast/IgpDetailsToast.tsx
src/features/transfer/TransferTokenForm.tsx

Ugly and hardcoding cases, not intended to be a permanent fix. Lots of people confused on Discord so adding this as a quick fix
* adds a more friendly message clearly telling what's needed
* Handles the case of TIA gas payments, before it was assumed only the native token was used

Quick fix for insufficient TIA for IGP gas

---

src/features/transfer/TransferTokenForm.tsx

Previously it was checking that a user's NTRN balance was enough to cover the required TIA balance

Check user's IGP token balance correctly when it isn't the native token on a Cosmos chain

---

package.json
src/components/toast/IgpDetailsToast.tsx
src/consts/values.ts
src/features/transfer/TransferTokenForm.tsx
src/features/transfer/useTokenTransfer.ts
src/features/transfer/utils.ts
yarn.lock

- Fix rounding issue with max amounts
- Upgrade sdk to 3.1.0-beta4
Fixes https://github.com/hyperlane-xyz/issues/issues/690
Corresponds with https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2913

Fix rounding issue with max amounts

---

.eslintrc
package.json
src/components/toast/IgpDetailsToast.tsx
src/consts/links.ts
src/features/store.ts
src/features/transfer/TransferTokenForm.tsx
src/features/transfer/types.ts
src/features/transfer/useIgpQuote.ts
src/features/transfer/useTokenTransfer.ts
src/features/transfer/validateForm.ts
yarn.lock

Ensure review details and balance validation handle all IGP exceptional cases
- Refactor IGP token selection into useIgpQuote hook
- Refactor form validation code for legibility
- DRY up code between useTokenTransfer and other IGP interactions
- Update to SDK 3.5.1 for cosmos token adapter fix
See #98 for preview build off neutron branch

IGP interaction refactor

---

src/consts/tokens.ts

Moving to the address from here https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3285/files#diff-222172cd8aed3cee9b9443be47ede2dd4df5a9c5ea8e7450bcb121ead1b3f5feR6 - I assume this is maybe a new address?

Plume - new warp address

---

package.json
src/context/context.ts
src/features/transfer/TransfersDetailsModal.tsx
src/features/transfer/useTokenTransfer.ts
src/features/transfer/utils.ts
src/features/wallet/SideBarMenu.tsx
src/features/wallet/hooks/cosmos.ts
src/features/wallet/hooks/evm.ts
src/features/wallet/hooks/solana.ts
src/features/wallet/hooks/types.ts
yarn.lock

- Update to 3.8.1 when it's published
- Use MultiProtocolCore to extract message ID for all protocols
- Surface message ID in transfer modal 
- Force double-check of current network in evm send tx function
- Improve types of multi-protocol send tx functions
- Handle error from missing token info in transfer history items
Fixes https://github.com/hyperlane-xyz/issues/issues/927

Extract Message ID and double-check evm network change

---

next.config.js
package.json
yarn.lock

Unlike the nexus and injectives branches atm, the ezeth already has the latest from main, including the registry changes which could introduce github rate limit issues when traffic from an IP is high. 
Related #200 #199

Main to ezeth

---

src/features/tokens/balances.ts

I was encountering the displayed balance to be the same with the remote balance when I set the recipient to the account to be the same as the sender. This will only happen when the sender and recipient are the same address, in other cases the webui displays correctly, e.g. the recipient is different from the sender. 
Changing `origin` at `src/features/tokens/balances.ts#44` to `destination` fixed. 
Configs:
```yaml
tokens:
- addressOrDenom: '0x4A679253410272dd5232B3Ff7cF5dbB88f295319'
chainName: geth45206
connections:
- token: ethereum|geth45207|0x4A679253410272dd5232B3Ff7cF5dbB88f295319
decimals: 18
logoURI: /logos/weth.png
name: Ether6
standard: EvmHypNative
symbol: ETH6
- addressOrDenom: '0x4A679253410272dd5232B3Ff7cF5dbB88f295319'
chainName: geth45207
connections:
- token: …
```

fix balance display when recipient is the same on the remote chain

---

.gitignore
README.md

Warp UI requires `projectId` from WallectConnect Cloud, but `README.md` does not mention it. This change fixes https://github.com/hyperlane-xyz/v3-docs/issues/85

Add documentation on WalletConnect Cloud project

---

src/components/tip/TipCard.tsx
src/consts/config.ts

Reverts hyperlane-xyz/hyperlane-warp-ui-template#236

Revert "tip box with info about issues"

---

src/features/chains/metadata.ts

Previously we declared all known cosmos chains to the wallet. Now it filters to just those used in the configured warp routes. This solves an error that was arsing from Stride chain

fix: Exclude unused cosmos chains from wallet connection

---

src/features/wallet/hooks/cosmos.ts

From #309:
- Ran into some issues with gas for the Celestia -> Eclipse transfers. I was able to repro the issue with Celestia -> Manta Pacific, which is interesting. The fix turned out to be to spend a bit more on fees -- I bumped our multiplier from 1.6 to 2, and both Celestia -> Mantapacific and Celestia -> Eclipse work now. This is the error I was getting prior to the fix:
The drive-by is a change that exists in the `nexus` branch -- I just checked out the whole file here

chore: increase the Cosmos gas estimate multiplier

---

src/features/chains/ChainSelectField.tsx
src/features/chains/ChainSelectModal.tsx
src/features/chains/hooks.ts
src/features/chains/utils.ts
src/features/transfer/TransferTokenForm.tsx

- Replace current chain menu with `ChainSearchMenu` from widgets
- Create a `chainMetadata` (not taken from the registry) with the tokens that come from the warpCore
- Create a `customListItemField` object that contains all the routes from a single chain to any other warp core token chain
- Chain Search Menu will show the routes from the opposing field. EX: If you open `"To"` chain, it will show all the routes from the `"From"` field chain to all the chains

feat: Chain Search Menu

---

package.json
src/components/banner/FormWarningBanner.tsx
src/components/banner/WarningBanner.tsx
src/components/layout/Card.tsx
src/features/chains/ChainConnectionWarning.tsx
src/features/chains/ChainSelectModal.tsx
src/features/chains/ChainWalletWarning.tsx
src/features/transfer/TransferTokenForm.tsx
yarn.lock

Fixes https://github.com/hyperlane-xyz/hyperlane-warp-ui-template/issues/215

feat: Add chain RPC health test and warning banner

---

src/features/transfer/TransferTokenForm.tsx

From https://github.com/hyperlane-xyz/hyperlane-warp-ui-template/pull/342 -  found this useful for test amounts of ETH (high decimal count, high value token)
Looks good on mobile: https://github.com/hyperlane-xyz/hyperlane-warp-ui-template/pull/342#discussion_r1873829038

feat: use 5 decimals for the displayed balance

---

src/consts/warpRouteWhitelist.ts

- Similar to #343, but on Nexus
- They indicated they wanted this route on Nexus because it's a common path for Eclipse users

feat: add ezSOL to Nexus

---

package.json
src/consts/warpRouteWhitelist.ts
yarn.lock

Adds USDC warp route that links appchain to base to nexus whitelist and bumps registry version

feat: add appchain base usdc route to nexus

---

src/consts/chains.ts

Essentially reverts https://github.com/hyperlane-xyz/hyperlane-warp-ui-template/pull/369

fix: use browser env vars for Solana and Injective RPC URLs

---

src/consts/chains.ts

basically reverts #370 and use injective variable as static instead

chore: remove dynamic var for injective and add static env

---

package.json
yarn.lock

- Moves to a new version of the registry that uses the newer version of the TONY/base-solanamainnet warp route.
- PR here intended for unwinding any existing bridged TONY https://github.com/hyperlane-xyz/hyperlane-warp-ui-template/pull/393

feat: move to new TONY warp route

---

package.json
src/components/buttons/ConnectAwareSubmitButton.tsx
src/components/buttons/SolidButton.tsx
src/consts/args.ts
src/consts/warpRouteWhitelist.test.ts
src/features/chains/ChainSelectField.tsx
src/features/chains/utils.ts
src/features/tokens/TokenSelectField.tsx
src/features/tokens/balances.ts
src/features/tokens/hooks.ts
src/features/transfer/RecipientConfirmationModal.tsx
src/features/transfer/TransferTokenForm.tsx
src/utils/queryParams.ts
vitest.config.mts
yarn.lock

Main to trump

---

package.json
src/consts/warpRouteWhitelist.ts
yarn.lock

- Post-migration LUMIA route. Uses a different lumiaprism router instead of the old lumia router
- fully tested manually locally

feat: update LUMIA route for migration

---

src/features/transfer/TransferTokenForm.tsx

Fixed a bug where if only one of the chain is defined and there is only one connection, when page is first loaded, it will show as "No Tokens Route Available"
Now only adds persistence when params are defined

fix: url params persistence when one chain is not defined

---

package.json
src/consts/warpRouteWhitelist.ts
yarn.lock

- Add all remaining WarpRouteIds to nexus. 
- Upgraded registry to 9.4.0
Routes added:
- USDC/arbitrum-base-endurance
- USDC/ethereum-form
- USDC.a/artela-base
- USDC/ethereum-superseed
- USDT/ethereum-form
-  USDT/ethereum-superseed
- WBTC/ethereum-form
- MAGIC/arbitrum-treasure
- WETH.a/artela-base
- fastUSD/ethereum-sei
- cbBTC/ethereum-superseed
- cbBTC/ethereum-flowmainnet
- ezETH/arbitrum-base-berachain-blast-bsc-ethereum-fraxtal-linea-mode-optimism-sei-swell-taiko-unichain-zircuit
- GAME/base-form
- AIXBT/base-form
- wstETH/ethereum-form
- pzETH/ethereum-swell-zircuit
- ART/artela-base-solanamainnet

chore: add all warp routes ids to nexus

---

src/features/tokens/TokenListModal.tsx

fix: show collateral address for relevant tokens
- fixes cases where we display the `HypERC20Collateral` address instead of the actual token address when we expect that
copy of https://github.com/hyperlane-xyz/hyperlane-warp-ui-template/pull/437

fix: show collateral address for relevant tokens

---

package.json
src/consts/warpRouteWhitelist.ts
yarn.lock

Adds the `MINT/mint-solanamainnet to nexus` warp route and updates the `@hyperlane-xyz/registry` package

feat: add MINT/mint-solanamainnet to nexus

---

package.json
src/consts/chains.ts
src/consts/warpRouteWhitelist.ts
src/features/tokens/TokenListModal.tsx
yarn.lock

- Adds the Sonic SVM routes to Nexus
- Tested locally
- Drive-by to make the width for the symbol wider, added to accommodate "sonicSOL". Screenshots attached:
Before:
After:

feat: add Sonic SVM routes to Nexus

---

src/consts/config.ts
src/features/chains/ChainSelectModal.tsx

Include `showAddChainButton` in the configs to allow overrides of chain metadata to add custom chain s

feat: showAddChainButton for chain search menu

---

src/consts/chains.ts

Add new environment variable for NEXT_PUBLIC_SONICSVM_RPC_URL override because main RPC is down

chore: add rpc url for sonicsvm to env variable

---

src/consts/warpRouteWhitelist.ts

Remove USDT/ethereum-superseed warp route from nexus

chore: remove ethereum superseed route

---

src/consts/warpRouteWhitelist.ts

Temporary remove `ETH/base-ethereum-lumiaprism` route

chore: remove ETH/base-ethereum-lumiaprism

---

src/consts/config.ts
src/features/tokens/hooks.ts
src/features/transfer/TransferTokenForm.tsx

Include `defaultDestinationChain` to config allowing the UI to have both default origin and destination chain
fixes #475

feat: add default destination chain to config

---

src/consts/warpRouteWhitelist.ts

This PR adds `TURTLE/ethereum-linea` to Nexus.
This warp route was already included in the registry [v10.15.0](https://github.com/hyperlane-xyz/hyperlane-registry/releases/tag/v10.15.0), which is why it can be directly merged into `nexus` as it already includes the required registry version.

chore: add `TURTLE/ethereum-linea`

---

src/consts/chains.ts

- Add environment variable for `ethereum` public RPC url
- Fixed an issue where RPC urls would be repeated because the [metadata merge](https://github.com/hyperlane-xyz/hyperlane-warp-ui-template/blob/55399638a3b5e893ba95c5716a93e86554c95f86/src/features/chains/metadata.ts#L56) would take both arrays
caveat: if the environment variable does not exist, array will be repeated twice (same as now) and empty arrays are not allowed because of the `safeParse` in the `chainMetadata`, ideally we would want the `mergeChainMetadataMap` to remove any duplicates
Before: 
After:

chore: add ethereum env variable for rpc and fix repeated RPC urls

---

package.json
src/features/wallet/context/EvmWalletContext.tsx
yarn.lock

Now the transactions signing will use a fallback RPC whenever one of the RPC fails instead of only having one point of failure. Also upgrade hyperlane packages that contains the needed changes for the RPC update
Reference: https://viem.sh/docs/clients/transports/fallback.html
How to test:
1 - With the current `main` branch, locally try doing a transaction with Ethereum or Arbitrum, they will more likely fail because of flakky RPC
2 - Do the same with this branch and the transactions will go through without issue, you can also check the network tab and see the requests going through

feat: include transport fallback for wagmiConfig

---

package.json
src/features/store.ts
src/features/transfer/TransferTokenForm.tsx
src/features/wallet/ConnectWalletButton.tsx
src/features/wallet/SideBarMenu.tsx
yarn.lock

This PR improves the way cosmos addresses are displayed. In cosmos there is like in Ethereum a private public key pair, but for every cosmos chain there is a different address prefix. Example Osmosis osmo1sduu..., Cosmos Hub cosmos1j48f33.., KYVE kyve1jhf738... and so on. Right now always the address of the first chain gets displayed which often has nothing to do with the chain the user has funds on and wants to swap from/to. This has caused confusion in the past.
This PR addresses this issue by showing the Cosmos Hub address by default if the user is connected with a cosmos wallet since Cosmos Hub is still the standard in the cosmos ecosystem. Once the user selects a cosmos origin chain that address is displayed instead.
TODO: once the monorepo PR …

chore: cosmos addresses

---

src/features/transfer/TransferTokenForm.tsx

Set `originChainName` during the effect phase instead of render phase

fix: set origin during effect instead of render

---

src/features/tokens/TokenListModal.tsx

chore: slightly increase width for token symbol and name

---

src/consts/warpRouteWhitelist.ts

Remove `SMOL/arbitrum-ethereum-solanamainnet-treasure` route

chore: remove smol route

---

src/consts/chains.ts
src/features/transfer/TransferTokenForm.tsx

Add SVM chains rent estimate amount on top of the IGP payment quoting, **this is purely presentational and the UI does not add on top of the actual transactions, the rent comes from the payment itself**. This is mean purely as a way to represent the actual fee paid for SVM bridging as close as possible
You can check the transactions and look at the rent paid to see how the estimates are taken:
[Solana](https://solscan.io/tx/53mvkbN21SM7PCv7CY98CDCXqxEhCXMPjtdsVZT6YNuRg98DEji7tkzXPsqjXpMGW3rAsdzZmwERv8CLrBX1BnsC#solBalanceChange): 0.00187224 + 0.00224112 = 0.00411336
[Eclipse](https://eclipsescan.xyz/tx/4xza8yohGKqBNd5QytFWRKLCgycJpYqohnhpKUB4Aen8Yx83jA28pPSE9naT7SHuvcUT2ytximkWF4G3559kvSj#balanceChange): 0.000018292 + 0.000021896 = 0.00004019 …

chore: add SVM rent estimate

---

.github/workflows/create-merge-prs.yaml

Set `fail-fast` to `false` for strategy, this will allow all branches to independently run instead of the matrix canceling in progress branches/pr creation if one of them fails. Ref: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast

chore: set fail-fast to false for create-merge-prs

---

package.json
yarn.lock

This pull request updates the version of the `@hyperlane-xyz/registry` dependency in `package.json` from `15.8.1` to `15.9.0`.

chore: bump registry to 15.9.0

---

package.json
yarn.lock

This pull request updates the version of the `@hyperlane-xyz/registry` dependency in the `package.json` file from `15.8.0` to `15.9.0`.

chore: main to nexus 15.9.0

---

src/features/store.ts
src/features/transfer/TransferTokenForm.tsx
src/features/warpCore/warpCoreConfig.ts

Fixes #595, this PR prevents the user from sending funds to a warp route address from the tokens list
- Create a `routerAddressesByChainMap` variable in store that host all the known `addressOrDenom` in a given chain
- Check if recipient is one of these addresses and if so, prevent transfer from being made

chore: prevent transfer from being sent to router addresses

---

src/consts/warpRouteWhitelist.ts

This pull request updates the `warpRouteWhitelist` constant in `src/consts/warpRouteWhitelist.ts` to include a new route for RDO.
* Added the `RDO/bsc-ethereum` route to the `warpRouteWhitelist` array.

chore: Add RDO to nexus

---

src/consts/warpRouteWhitelist.test.ts
src/features/warpCore/warpCoreConfig.ts

uppercase `warpRouteIds` and `whiteList` ids to fix discrepancy

chore: uppercase warpRouteIds and whiteList

---

src/consts/warpRouteWhitelist.ts

Remove `TRUMP/solanamainnet-trumpchain` from route whitelist

chore: remove trump chain route

---

package.json
src/consts/warpRouteWhitelist.ts
yarn.lock

This PR bumps registry to v17.5.0 and add taiko warp route

chore: Bump registry to v17.5.0 and add taiko warp route

---

package.json
src/consts/warpRouteWhitelist.ts
yarn.lock

This PR bumps registry to 17.7.0 and adds toshi to whitelist

chore: Bump nexus to 17.7.0

---

src/consts/warpRouteWhitelist.test.ts
src/consts/warpRouteWhitelist.ts

Now instead of only relying on published warp routes, it will first attempt to fetch warp routes from the registry for the warp route white list test

chore: update warp route white list test to include github registry

---

src/features/limits/const.ts

Increase limit to 5000 USDC for multi-collateral USDC routes

chore: increase limit for USDC

---

src/consts/warpRouteWhitelist.ts

Include `SEDA/base-ethereum` to nexus
[base -> ethereum](https://explorer.hyperlane.xyz/message/0xb37bee8572082838db97f88b11f315cb59f67269075259187832ba1dc4ac5015)
[ethereum -> base](https://explorer.hyperlane.xyz/message/0x8115bd726f8658b3e19d67f0e307bb50156586d33eabe338b693e8fbdde95601)

chore: add seda route to whitelist

---

package.json
yarn.lock

Bump `@types/nodes` because of upcoming Vercel node v18 deprecation

chore: bump @types/nodes to v22

---

src/consts/warpRouteWhitelist.ts
src/consts/warpRoutes.ts

- Remove `TIA/arbitrum-neutron` route
- Remove IBC transfer connection to arbitrum from neutron

chore: remove TIA/arbitrum-neutron route from nexus

---

src/features/transfer/TransferTokenForm.tsx
src/features/transfer/fees.ts
src/features/transfer/maxAmount.ts
src/features/transfer/useFeeQuotes.ts

This PR allows the maxTransfer button to check for route with lowest fee before setting the amount
- Gets route with lowest fee for max transfer button
- Fixed a bug where `getLowestFeeTransferToken` would use plain `amount` instead of `amountWei`

feat: multi-collateral warp routes maxTransfer
